dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake3
      - libmongo-client-dev
      - libmongo-client0

install:
    - export CC=gcc-7
    - export CXX=g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake -DNDB_ENGINE_SQLITE=ON -DNDB_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release
  - make
  - make test